apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  selector:
    matchLabels:
      app: helloaspnetlinux
  replicas: 2
  template:
    metadata:
      labels:
        app: helloaspnetlinux
    spec:
      containers:
        - name: helloaspnetlinux
          image: abhimasum2.azurecr.io/dotnetcorepipeline
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: helloloadbalencer-service
spec:
  selector:
    app: helloaspnetlinux
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
